language: python

python:
  - "3.6"
  - "3.7"

install:
  - pip3 install --upgrade pip
  - pip install -r requirements.txt

script:
  - pytest --pylint
  - pytest --pycodestyle
  - pytest --pydocstyle
